Better documentation for buzz user function
SwarmUS/HiveMind pull request #80
Opened 2021-04-12 21:53 UTC by xgroleau

2021-04-12 22:12 UTC, t-constantin requested changes
Small typo corrections needed

2021-04-12 22:12 UTC, t-constantin commented on src/bittybuzz/include/bittybuzz/BittyBuzzUserFunctions.h
> +     * The table description of the arguments is an array of tuple, the
tuple"s"

2021-04-12 22:12 UTC, t-constantin commented on src/bittybuzz/include/bittybuzz/BittyBuzzUserFunctions.h
> +     * The table description of the arguments is an array of tuple, the
"... is an array of tuples, which hold the arg name as key and a value that can be of any type. Only the type is checked."
would probably be better

2021-04-12 22:12 UTC, t-constantin commented on src/bittybuzz/include/bittybuzz/BittyBuzzUserFunctions.h
> +     *    .0 = {.arg_int=0}, // We juste pass value so the type is registered
typo: just

2021-04-12 22:12 UTC, t-constantin commented on src/bittybuzz/include/bittybuzz/BittyBuzzUserFunctions.h
> +     * The table argument must be by index from 0 to N-1 args.
typo: argument"s"

2021-04-13 12:10 UTC, stlaperriere requested changes

2021-04-13 12:10 UTC, stlaperriere commented on src/bittybuzz/include/bittybuzz/BittyBuzzUserFunctions.h
> +     *@details This closure expects tree parameters.
Do you mean "three" (3) parameters?

2021-04-13 12:16 UTC, xgroleau commented on src/bittybuzz/include/bittybuzz/BittyBuzzUserFunctions.h
> +     *@details This closure expects tree parameters.
:deciduous_tree:  :deciduous_tree:

2021-04-13 12:20 UTC, stlaperriere approved these changes

2021-04-13 12:21 UTC, t-constantin approved these changes

2021-04-13 13:16 UTC, merged